
import { Coin, BlogPost, P2PAd } from './types';

export const INITIAL_COINS: Coin[] = [
  {
    id: 'bitcoin',
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 64230.50,
    change24h: 2.45,
    marketCap: '1.2T',
    volume24h: '35.2B',
    sparkline: [62000, 62500, 63100, 62800, 63500, 64230],
  },
  {
    id: 'ethereum',
    symbol: 'ETH',
    name: 'Ethereum',
    price: 3450.20,
    change24h: -1.20,
    marketCap: '415B',
    volume24h: '18.4B',
    sparkline: [3550, 3500, 3480, 3520, 3460, 3450],
  },
  {
    id: 'solana',
    symbol: 'SOL',
    name: 'Solana',
    price: 145.75,
    change24h: 5.67,
    marketCap: '65B',
    volume24h: '4.2B',
    sparkline: [130, 135, 142, 138, 144, 145],
  },
  {
    id: 'cardano',
    symbol: 'ADA',
    name: 'Cardano',
    price: 0.45,
    change24h: 0.12,
    marketCap: '16B',
    volume24h: '400M',
    sparkline: [0.44, 0.45, 0.46, 0.45, 0.44, 0.45],
  },
  {
    id: 'polkadot',
    symbol: 'DOT',
    name: 'Polkadot',
    price: 7.20,
    change24h: -3.45,
    marketCap: '10B',
    volume24h: '250M',
    sparkline: [7.50, 7.60, 7.40, 7.30, 7.15, 7.20],
  }
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Future of Institutional Crypto Adoption',
    excerpt: 'How major banks are shifting their perspective on digital assets in 2024 and beyond.',
    content: 'Institutional interest in cryptocurrency has reached an all-time high. With the approval of various spot ETFs, the floodgates have opened for traditional finance players to enter the ecosystem with regulatory clarity...',
    author: 'Sarah Jenkins',
    date: 'Oct 12, 2024',
    category: 'Institutional',
    readTime: '5 min read',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '2',
    title: 'Understanding Macro Trends in DeFi',
    excerpt: 'Exploring the intersection of global interest rates and decentralized finance yields.',
    content: 'As central banks navigate the complex landscape of inflation and interest rates, the DeFi sector is seeing a renewed focus on sustainable yields and real-world asset integration...',
    author: 'Marcus Thorne',
    date: 'Oct 10, 2024',
    category: 'Analysis',
    readTime: '8 min read',
    imageUrl: 'https://images.unsplash.com/photo-1611974717482-48cd91000c14?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '3',
    title: 'Nexus AI: Your New Trading Advantage',
    excerpt: 'Leveraging large language models for sentiment analysis and market prediction.',
    content: 'The introduction of Gemini-powered insights into the Nexus platform represents a paradigm shift for retail traders. By processing millions of data points in seconds...',
    author: 'AI Editorial Team',
    date: 'Oct 08, 2024',
    category: 'Technology',
    readTime: '4 min read',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800'
  }
];

export const MOCK_P2P_ADS: P2PAd[] = [
  {
    id: 'p2p-1',
    advertiser: 'CryptoElite_OTC',
    orders: 1245,
    completionRate: 99.8,
    price: 1.01,
    currency: 'USD',
    available: 15420.50,
    limitMin: 100,
    limitMax: 5000,
    paymentMethods: ['Bank Transfer', 'Zelle'],
    type: 'BUY',
    asset: 'USDT',
    isVerified: true,
  },
  {
    id: 'p2p-2',
    advertiser: 'GlobalSwap_Express',
    orders: 856,
    completionRate: 98.2,
    price: 1.02,
    currency: 'USD',
    available: 5000.00,
    limitMin: 50,
    limitMax: 2000,
    paymentMethods: ['PayPal', 'Wise'],
    type: 'BUY',
    asset: 'USDT',
    isVerified: true,
  },
  {
    id: 'p2p-3',
    advertiser: 'FastTrade_Pro',
    orders: 432,
    completionRate: 95.5,
    price: 0.99,
    currency: 'USD',
    available: 25000.00,
    limitMin: 500,
    limitMax: 25000,
    paymentMethods: ['Revolut', 'Bank Transfer'],
    type: 'SELL',
    asset: 'USDT',
    isVerified: false,
  },
  {
    id: 'p2p-4',
    advertiser: 'Bitcoin_Merchant_NY',
    orders: 3102,
    completionRate: 100,
    price: 64500.00,
    currency: 'USD',
    available: 1.25,
    limitMin: 1000,
    limitMax: 80000,
    paymentMethods: ['Wire Transfer'],
    type: 'BUY',
    asset: 'BTC',
    isVerified: true,
  }
];
